In [3]:
import pandas as pd
import numpy as np
import random

np.random.seed(42)
n = 50

names = [
    'Aarav', 'Priya', 'Rohit', 'Sneha', 'Arjun', 'Pooja', 'Vikram', 'Neha',
    'Karan', 'Anjali', 'Rahul', 'Divya', 'Amit', 'Shreya', 'Suresh', 'Kavya',
    'Ravi', 'Meera', 'Aditya', 'Nisha', 'Varun', 'Simran', 'Manish', 'Ritika',
    'Deepak', 'Tanvi', 'Sanjay', 'Komal', 'Nikhil', 'Ananya'
]

df = pd.DataFrame({
    'name': [random.choice(names) for _ in range(n)],
    'age': np.random.randint(21, 65, n),
    'gender': np.random.choice(['Male', 'Female'], n),
    'income': np.random.randint(20000, 200000, n),
    'loan_amount': np.random.randint(5000, 100000, n),
    'credit_score': np.random.randint(300, 850, n),
    'employment_years': np.random.randint(0, 30, n),
    'education': np.random.choice(['Graduate', 'Not Graduate'], n),
    'property_area': np.random.choice(['Urban', 'Rural', 'Semiurban'], n),
    'married': np.random.choice(['Yes', 'No'], n),
    'loan_status': np.random.choice(['Approved', 'Rejected', 'Pending'], n, p=[0.6, 0.3, 0.1])
})

df.loc[np.random.choice(n, 50), 'credit_score'] = np.nan
df.loc[np.random.choice(n, 30), 'income'] = np.nan
df.loc[np.random.choice(n, 20), 'employment_years'] = np.nan
df.index = range(1, n+1)
print(df.shape)
df.head(50)

(50, 11)


,name,age,gender,income,loan_amount,credit_score,employment_years,education,property_area,married,loan_status
1,Meera,59,Male,190171.0,59268,NaN,0.0,Not Graduate,Rural,No,Approved
2,Ananya,49,Female,159643.0,92939,NaN,15.0,Graduate,Urban,Yes,Pending
3,Ritika,35,Male,58044.0,23141,NaN,29.0,Not Graduate,Rural,No,Approved
4,Aditya,63,Female,NaN,85356,NaN,11.0,Not Graduate,Urban,Yes,Rejected
5,Suresh,28,Male,134752.0,76910,NaN,4.0,Not Graduate,Rural,No,Approved
6,Divya,41,Female,68984.0,61044,685.0,4.0,Not Graduate,Semiurban,No,Approved
7,Aditya,59,Male,NaN,72214,686.0,26.0,Not Graduate,Urban,Yes,Rejected
8,Aditya,39,Male,22568.0,38827,NaN,22.0,Graduate,Urban,Yes,Approved
9,Nisha,43,Female,NaN,60820,380.0,8.0,Graduate,Urban,No,Approved
10,Amit,31,Male,NaN,67623,NaN,8.0,Graduate,Urban,Yes,Pending


In [4]:
#basics of EDA using pandas
   
print("shape :\n",df.shape)
print("top 5 rows are :\n",df.head())
print("bottom 5 rows are :\n",df.tail())
print(df.info())  
print(df.describe()) 
print(df.dtypes )

shape :
 (50, 11)
top 5 rows are :
      name  age  gender    income  loan_amount  credit_score  employment_years  \
1   Meera   59    Male  190171.0        59268           NaN               0.0   
2  Ananya   49  Female  159643.0        92939           NaN              15.0   
3  Ritika   35    Male   58044.0        23141           NaN              29.0   
4  Aditya   63  Female       NaN        85356           NaN              11.0   
5  Suresh   28    Male  134752.0        76910           NaN               4.0   

      education property_area married loan_status  
1  Not Graduate         Rural      No    Approved  
2      Graduate         Urban     Yes     Pending  
3  Not Graduate         Rural      No    Approved  
4  Not Graduate         Urban     Yes    Rejected  
5  Not Graduate         Rural      No    Approved  
bottom 5 rows are :
      name  age  gender    income  loan_amount  credit_score  employment_years  \
46   Neha   29    Male  139176.0        39766           NaN    

In [5]:
print( df.duplicated().sum())
print(df.isnull())
print(df.isnull().sum())


0
     name    age  gender  income  loan_amount  credit_score  employment_years  \
1   False  False   False   False        False          True             False   
2   False  False   False   False        False          True             False   
3   False  False   False   False        False          True             False   
4   False  False   False    True        False          True             False   
5   False  False   False   False        False          True             False   
6   False  False   False   False        False         False             False   
7   False  False   False    True        False         False             False   
8   False  False   False   False        False          True             False   
9   False  False   False    True        False         False             False   
10  False  False   False    True        False          True             False   
11  False  False   False    True        False         False             False   
12  False  False   False  

In [6]:
print(df['credit_score'].isnull().sum())

33


In [7]:
median=df['credit_score'].median()
print(median)
mean=df['income'].mean()
print(mean)
med=df['employment_years'].median()
print(med)

593.0
112133.33333333333
15.0


In [8]:
df['credit_score'] = df['credit_score'].fillna(df['credit_score'].median())
df['income'] = df['income'].fillna(df['income'].median())
df['employment_years'] = df['employment_years'].fillna(df['employment_years'].median())


print(df.isnull().sum())

name                0
age                 0
gender              0
income              0
loan_amount         0
credit_score        0
employment_years    0
education           0
property_area       0
married             0
loan_status         0
dtype: int64


In [9]:
print(df)

      name  age  gender    income  loan_amount  credit_score  \
1    Meera   59    Male  190171.0        59268         593.0   
2   Ananya   49  Female  159643.0        92939         593.0   
3   Ritika   35    Male   58044.0        23141         593.0   
4   Aditya   63  Female  130989.0        85356         593.0   
5   Suresh   28    Male  134752.0        76910         593.0   
6    Divya   41  Female   68984.0        61044         685.0   
7   Aditya   59    Male  130989.0        72214         686.0   
8   Aditya   39    Male   22568.0        38827         593.0   
9    Nisha   43  Female  130989.0        60820         380.0   
10    Amit   31    Male  130989.0        67623         593.0   
11  Shreya   31  Female  130989.0        86734         301.0   
12  Suresh   44  Female  199262.0        80450         593.0   
13    Amit   56  Female  156330.0        98426         593.0   
14    Ravi   60  Female   59504.0        27299         684.0   
15  Ritika   44  Female  184231.0       

In [21]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
cols=['age','income','loan_amount','credit_score']
print(scaler.fit_transform(df[cols]))




[[0.88095238 0.94854947 0.55960635 0.57367387]
 [0.64285714 0.7757762  0.92494819 0.57367387]
 [0.30952381 0.20077648 0.16761607 0.57367387]
 [0.97619048 0.61360884 0.84267005 0.57367387]
 [0.14285714 0.63490554 0.75102807 0.57367387]
 [0.45238095 0.26269143 0.57887656 0.75442043]
 [0.88095238 0.61360884 0.70007487 0.75638507]
 [0.4047619  0.         0.33781452 0.57367387]
 [0.5        0.61360884 0.57644608 0.15520629]
 [0.21428571 0.61360884 0.65026095 0.57367387]
 [0.21428571 0.61360884 0.85762182 0.        ]
 [0.52380952 1.         0.78943828 0.57367387]
 [0.80952381 0.75702627 0.98448401 0.57367387]
 [0.9047619  0.20903936 0.21273179 0.7524558 ]
 [0.52380952 0.91493203 0.44369215 0.78781925]
 [0.02380952 0.06462019 0.66567929 0.57367387]
 [0.47619048 0.33555186 0.432538   0.57367387]
 [0.         0.61360884 0.50331478 0.81335953]
 [0.52380952 0.05714965 0.         0.57367387]
 [1.         0.20426274 0.72122218 0.57367387]
 [0.66666667 0.61360884 0.25222703 0.39489194]
 [0.85714286 

In [22]:
print(df[cols].head())

        age    income  loan_amount  credit_score
1  0.880952  0.948549     0.559606      0.573674
2  0.642857  0.775776     0.924948      0.573674
3  0.309524  0.200776     0.167616      0.573674
4  0.976190  0.613609     0.842670      0.573674
5  0.142857  0.634906     0.751028      0.573674
